DROP TABLE IF EXISTS Maps;
DROP TABLE IF EXISTS GameStats;
DROP TABLE IF EXISTS UserStats;
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (id INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT, username VARCHAR(255) NOT NULL, password CHAR(256) NOT NULL, salt CHAR(20) NOT NULL);
CREATE TABLE UserStats (user_id INTEGER PRIMARY KEY NOT NULL, wins INTEGER, losses INTEGER, games INTEGER, FOREIGN KEY(user_id) REFERENCES Users(id));
CREATE TABLE GameStats (id INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT, player_one INTEGER NOT NULL, player_two INTEGER NOT NULL, winner INTEGER NOT NULL, player_one_rounds INTEGER NOT NULL, player_two_rounds INTEGER NOT NULL, FOREIGN KEY(player_one) REFERENCES Users(id),  FOREIGN KEY(player_two) REFERENCES Users(id));
CREATE TABLE Maps (id INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT, map_name VARCHAR(255) NOT NULL, map_string TEXT NOT NULL);
